# Generated by Django 2.0.3 on 2018-08-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20180805_0510'),
        ('accounts', '0003_user_follow_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_blog',
            field=models.ManyToManyField(to='apis.Insource'),
        ),
    ]
