# Generated by Django 2.0.3 on 2018-09-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_remove_provider_writer'),
        ('accounts', '0004_user_like_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='writer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='apis.Provider'),
        ),
    ]
