# Generated by Django 2.0.3 on 2018-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180910_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterRegistration',
            fields=[
                ('request_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('held_for_review', 'Held for Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='held_for_review', max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
