<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-06-04 11:06
=======
# Generated by Django 2.0.3 on 2018-06-08 10:38
>>>>>>> 4ed08002e9b19bc24f8ab5694c15ea74035fdb9d

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=70)),
                ('wrote_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Category',
            fields=[
                ('category_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 4ed08002e9b19bc24f8ab5694c15ea74035fdb9d
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('feedback_message', models.TextField()),
                ('email', models.EmailField(max_length=90)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=60)),
                ('url', models.URLField(blank=True, null=True)),
                ('favicon_url', models.URLField(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
<<<<<<< HEAD
=======
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Category'),
        ),
        migrations.AddField(
            model_name='blog',
>>>>>>> 4ed08002e9b19bc24f8ab5694c15ea74035fdb9d
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Provider'),
        ),
    ]
