# Generated by Django 2.0.3 on 2018-06-11 09:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('apis', '0002_auto_20180607_1720'),
    ]

    operations = [
       migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apis.Category'),
            preserve_default=False,
        ),
    ]
