# Generated by Django 2.0.3 on 2018-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20180717_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
