# Generated by Django 2.0.3 on 2018-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_provider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
