# Generated by Django 2.0.3 on 2018-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20180611_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
