# Generated by Django 2.0.3 on 2018-07-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20180720_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
