# Generated by Django 2.0.3 on 2018-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20180722_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
