# Generated by Django 2.0.3 on 2018-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_blog_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
