# Generated by Django 2.0.3 on 2018-08-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20180731_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='insource',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
