# Generated by Django 2.0.3 on 2018-08-06 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0010_auto_20180805_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='writer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
