# Generated by Django 2.0.3 on 2018-08-25 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='insource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Insource'),
            preserve_default=False,
        ),
    ]
