# Generated by Django 2.0.3 on 2018-09-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20180826_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='writer',
        ),
    ]
